# Добавь эти location блоки внутрь своего server {} блока в nginx.conf
# После добавления: sudo nginx -t && sudo systemctl reload nginx

location /api/login {
    proxy_pass https://functions.poehali.dev/0faae4ff-54b8-40f4-988a-aa6bbebd01f0;
    proxy_ssl_server_name on;
    proxy_set_header Content-Type "application/json";
    add_header Access-Control-Allow-Origin *;
}

location /api/users {
    proxy_pass https://functions.poehali.dev/93e60fdd-bf88-468d-88c8-f312a5f61460;
    proxy_ssl_server_name on;
    proxy_set_header Content-Type "application/json";
    add_header Access-Control-Allow-Origin *;
}

location /api/orders {
    proxy_pass https://functions.poehali.dev/ec65c93f-9552-4d66-a9f5-4949602f6cf4;
    proxy_ssl_server_name on;
    proxy_set_header Content-Type "application/json";
    add_header Access-Control-Allow-Origin *;
}

location /api/orgs {
    proxy_pass https://functions.poehali.dev/ae73137e-e58d-4e74-abea-c2dafc76ed7d;
    proxy_ssl_server_name on;
    proxy_set_header Content-Type "application/json";
    add_header Access-Control-Allow-Origin *;
}